import React, { useState } from 'react';
import { 
  FileText, 
  BarChart3, 
  Sparkles, 
  Copy, 
  Check, 
  Download, 
  Send, 
  Slack, 
  Mail, 
  ShieldCheck, 
  AlertTriangle, 
  TrendingUp,
  RefreshCw
} from 'lucide-react';
import { Repository, Finding, SecurityAlert, DependencyPackage } from '../types';

interface ExecutiveDigestProps {
  repository: Repository;
  findings: Finding[];
  securityAlerts: SecurityAlert[];
  dependencies: DependencyPackage[];
}

export const ExecutiveDigest: React.FC<ExecutiveDigestProps> = ({
  repository,
  findings,
  securityAlerts,
  dependencies
}) => {
  const [reportType, setReportType] = useState<'daily' | 'weekly' | 'security_audit'>('daily');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);
  const [slackSent, setSlackSent] = useState<boolean>(false);
  const [digestContent, setDigestContent] = useState<string>(`# 🐸 Git-Frog Repository Health & Security Digest
**Repository:** ${repository.owner}/${repository.name} (${repository.branch})
**Date:** ${new Date().toISOString().slice(0, 10)}
**Overall Health Score:** ${repository.healthScore}/100

---

### Executive Summary
The **Reporter Agent** has completed the continuous sweep for **${repository.name}**.
- **Active Critical Findings:** ${securityAlerts.filter(a => a.severity === 'critical').length}
- **Open PRs Analyzed:** ${repository.openPRs}
- **Dependency Health Index:** ${repository.dependencyHealthScore}%

### 🚨 Security & Vulnerability Highlights
1. **${securityAlerts[0]?.title || 'Hardcoded Secret Check'}**
   - *Severity:* ${securityAlerts[0]?.severity.toUpperCase() || 'CRITICAL'}
   - *Status:* Auto-Redacted by Policy Agent. Remediation patch drafted by Refiner Agent.

### 📦 Dependency & Upgrade Risk Matrix
- **${dependencies[0]?.name || 'express'}**: Upgradable from ${dependencies[0]?.currentVersion || '4.21.0'} to ${dependencies[0]?.latestVersion || '4.21.2'} (Low breaking risk).

---
*Report auto-generated by Git-Frog Reporter Agent v2.4 (Gemini 3.6 Flash Engine).*`);

  const handleGenerateLiveDigest = async () => {
    setIsGenerating(true);
    try {
      const response = await fetch('/api/generate-digest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          repoName: repository.name,
          healthScore: repository.healthScore,
          reportType,
          findingsCount: findings.length,
          alertsCount: securityAlerts.length,
          depsCount: dependencies.length
        })
      });

      const data = await response.json();
      if (data.markdown) {
        setDigestContent(data.markdown);
      }
    } catch (err) {
      console.error('Failed to generate digest via server:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(digestContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([digestContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `git-frog-digest-${repository.name}-${reportType}.md`;
    link.click();
  };

  const handleSendSlack = () => {
    setSlackSent(true);
    setTimeout(() => setSlackSent(false), 2500);
  };

  return (
    <div className="space-y-5 font-mono text-xs">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-sky-500/10 text-sky-400 border border-sky-500/30">
            <BarChart3 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white tracking-wide flex items-center gap-2">
              REPORTER AGENT • EXECUTIVE DIGEST STUDIO
            </h3>
            <p className="text-slate-400 font-sans text-xs">
              Automated executive security summaries, team slack updates & release compliance reports
            </p>
          </div>
        </div>

        {/* Report Frequency Selector */}
        <div className="flex items-center gap-1.5 bg-[#10131A] p-1 rounded-xl border border-slate-800">
          {(['daily', 'weekly', 'security_audit'] as const).map((type) => (
            <button
              key={type}
              onClick={() => setReportType(type)}
              className={`px-3 py-1.5 rounded-lg uppercase transition-all cursor-pointer ${
                reportType === type
                  ? 'bg-sky-400 text-black font-bold'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {type.replace('_', ' ')}
            </button>
          ))}
        </div>
      </div>

      {/* Action Bar */}
      <div className="p-4 rounded-xl bg-[#10131A] border border-slate-800 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3 text-slate-300">
          <Sparkles className="w-4 h-4 text-sky-400" />
          <span>Generator Mode: <strong className="text-white">Gemini 3.6 Flash Executive Engine</strong></span>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleGenerateLiveDigest}
            disabled={isGenerating}
            className="px-4 py-2 rounded-lg bg-sky-400 hover:bg-sky-300 text-black font-bold uppercase transition-all flex items-center gap-1.5 cursor-pointer shadow-[0_0_12px_rgba(56,189,248,0.3)]"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? 'animate-spin' : ''}`} />
            {isGenerating ? 'Synthesizing Digest...' : 'Generate Fresh Digest'}
          </button>

          <button
            onClick={handleCopyMarkdown}
            className="px-3.5 py-2 rounded-lg bg-[#08090D] border border-slate-800 hover:border-slate-700 text-slate-300 hover:text-white transition-all flex items-center gap-1.5 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied MD' : 'Copy MD'}
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="px-3.5 py-2 rounded-lg bg-[#08090D] border border-slate-800 hover:border-slate-700 text-slate-300 hover:text-white transition-all flex items-center gap-1.5 cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-cyan-400" />
            Download MD
          </button>

          <button
            onClick={handleSendSlack}
            className="px-3.5 py-2 rounded-lg bg-indigo-600/20 border border-indigo-500/40 text-indigo-300 hover:bg-indigo-600/30 transition-all flex items-center gap-1.5 cursor-pointer"
          >
            <Send className="w-3.5 h-3.5" />
            {slackSent ? 'Dispatched to #security-alerts!' : 'Dispatch to Slack'}
          </button>
        </div>
      </div>

      {/* Report Preview Canvas */}
      <div className="p-6 rounded-2xl bg-[#050608] border border-slate-800 shadow-inner font-mono text-slate-300 whitespace-pre-wrap leading-relaxed max-h-[500px] overflow-y-auto">
        {digestContent}
      </div>
    </div>
  );
};
